SIL.Web/ViewModels/WebsiteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.WebPages.Html;
using SIL.Domain;
using System.Web.Mvc;
using SIL.Core.Common;
using System.ComponentModel.DataAnnotations;

namespace SIL.Web.ViewModels
{
    public class WebsiteViewModel
    {
        public int WebsiteId { get; set; }
        public int CustomerId { get; set; }
        public int IpId { get; set; }


        public virtual IEnumerable<System.Web.Mvc.SelectListItem> Ips { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> Customers { get; set; }

        public string WebsitePath { get; set; }
        public string WebsiteFolder { get; set; }
        public string DatabaseName { get; set; }
        public string Version { get; set; }
        public string SiteName { get; set; }
        public string URL { get; set; }
        public bool IsActive { get; set; }
        public bool DomainControl { get; set; }
        public string ServerName { get; set; }
        public string SupportUsername { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string SupportPasswordHash { get; set; }
        //public string Password
        //{
        //    set { SupportPasswordHash = Md5Encrypt.Md5EncryptPassword(value); }
        //}
        public string Comments { get; set; }
        public bool Pingdom { get; set; }
 
     
         
    }
}

SIL.Web/Controllers/WebsiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using SIL.CommadProcessor.Dispatcher;
using SIL.DataLayer.Repositories;
using SIL.DataLayer.Repositories.Interfaces;
using SIL.DataLayer.Repository;
using SIL.Domain;
using SIL.Service.Commands.Website;
using SIL.Web.Core;
using SIL.Web.Core.ActionFilters;
using SIL.Web.Core.Models;
using SIL.Web.Helpers;
using SIL.Web.ViewModels;

namespace SIL.Controllers
{
    [CompressResponse]
    [SILAuthorise(Roles.User, Roles.Admin)]
    public class WebsiteController : Controller
    {
        //
        // GET: /Website/

        private readonly ICommandBus commandBus;
        private readonly IWebsiteRepository websiteRepository;
        private readonly ICompanyRepository customerRepository;
        private readonly IServerRepository serverRepository;
        private readonly IIpRepository ipRepository;


        public WebsiteController(ICommandBus commandBus, IWebsiteRepository websiteRepository, ICompanyRepository customerRepository, IIpRepository ipRepository, IServerRepository serverRepository)
        {
            this.websiteRepository = websiteRepository;
            this.commandBus = commandBus;
            this.customerRepository = customerRepository;
            this.ipRepository = ipRepository;
            this.serverRepository = serverRepository;
        }

        public ActionResult Index()
        {
            var websites = websiteRepository.GetAll();
            return View("Index",websites);
        }

        public ActionResult Details(int id =0)
        {
            var web = websiteRepository.GetById(id);
            var viewModel = Mapper.Map<Website, WebsiteViewModel>(web);
            var servers = serverRepository.GetAll();
            var ips = ipRepository.GetAll();
            var customers = customerRepository.GetAll();


            //viewModel.Servers = servers.ToSelectListOfServers(web.ServerId);
            viewModel.Ips = ips.ToSelectListOfIps(web.IpId);
            viewModel.Customers = customers.ToSelectListOfCustomers(web.CustomerId);
            return View(viewModel);
        }


        public ActionResult Create()
        {
            var viewModel = new WebsiteViewModel();
            var customers = customerRepository.GetAll();
 
            var ips = ipRepository.GetAll();

            viewModel.Customers = customers.ToSelectListOfCustomers(-1);
       //     viewModel.Servers = servers.ToSelectListOfServers(-1);
            viewModel.Ips = ips.ToSelectListOfIps(-1);

            viewModel.SupportUsername = " ";
 
            return View(viewModel);
        }
       

        [HttpPost]
        public ActionResult Save(WebsiteViewModel web)
        {

            if (ModelState.IsValid)
            {
                var command = Mapper.Map<WebsiteViewModel, CreateOrUpdateWebsiteCommand>(web);
                var result = commandBus.Submit(command);

                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            // Would ideally like to do one call to get everything - Looking into

            var servers = serverRepository.GetAll();
            var ips = ipRepository.GetAll();
            var customers = customerRepository.GetAll();

            web.Customers = customers.ToSelectListOfCustomers(web.CustomerId);       
            //web.Servers = servers.ToSelectListOfServers(web.ServerId);
            web.Ips = ips.ToSelectListOfIps(web.IpId);
        
            if (web.WebsiteId == 0)
            {
                return View("Create", web);
            }
            else
            {
                return View("Edit", web);
            }            
        }

        public ActionResult Edit(int id)      
        {
            var web = websiteRepository.GetById(id);
            var viewModel = Mapper.Map<Website, WebsiteViewModel>(web);

            var ips = ipRepository.GetAll();
            var customers = customerRepository.GetAll();

            viewModel.Customers = customers.ToSelectListOfCustomers(web.CustomerId);
            viewModel.Ips = ips.ToSelectListOfIps(web.IpId);
            return View(viewModel);


        }


    
        public ActionResult Delete(int id)
        {
            var command = new DeleteWebsiteCommand { WebsiteId = id };            
            var result = commandBus.Submit(command);
            var websites = websiteRepository.GetAll();
            return View(websites);

        }

    }
}

SIL.Web/Views/Website/Create.cshtml
@model SIL.Web.ViewModels.WebsiteViewModel

@{
    ViewBag.Title = "Create";
}

<h1 class="pull-left">Create</h1>


<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<span id="rightPane">


<div>
@using (Html.BeginForm("Save", "Website")) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Website</legend>

        <span class="editor-label">
            @Html.LabelFor(model => model.SiteName)
            @Html.EditorFor(model => model.SiteName)
            @Html.ValidationMessageFor(model => model.SiteName)
        </span>

        <span>
            @Html.LabelFor(model => model.WebsitePath)
            @Html.EditorFor(model => model.WebsitePath)
            @Html.ValidationMessageFor(model => model.WebsitePath)
        </span>

        <span>
            @Html.LabelFor(model => model.WebsiteFolder)
            @Html.EditorFor(model => model.WebsiteFolder)
            @Html.ValidationMessageFor(model => model.WebsiteFolder)
        </span>

        <span>
            @Html.LabelFor(model => model.DatabaseName)
            @Html.EditorFor(model => model.DatabaseName)
            @Html.ValidationMessageFor(model => model.DatabaseName)
         </span>

        <span>
            @Html.LabelFor(model => model.Version)
            @Html.EditorFor(model => model.Version)
            @Html.ValidationMessageFor(model => model.Version)
        </span>
        <span>
            @Html.LabelFor(model => model.URL)
            @Html.EditorFor(model => model.URL)
            @Html.ValidationMessageFor(model => model.URL)
        </span>

         <span>
            @Html.LabelFor(model => model.IsActive)
              @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </span>

        <span>
            @Html.LabelFor(model => model.DomainControl)
            @Html.EditorFor(model => model.DomainControl)
            @Html.ValidationMessageFor(model => model.DomainControl)
         </span>

        <span>
            @Html.LabelFor(model => model.ServerName)
            @Html.EditorFor(model => model.ServerName)
            @Html.ValidationMessageFor(model => model.ServerName)
        </span>




        <span>
            @Html.LabelFor(model => model.Comments)
            @Html.EditorFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </span>

        <span>
            @Html.LabelFor(model => model.Pingdom)
            @Html.EditorFor(model => model.Pingdom)
            @Html.ValidationMessageFor(model => model.Pingdom)
        </span>

                        <span>
            @Html.Label("Customers")          
            @Html.DropDownListFor(model => model.CustomerId , Model.Customers,"--Select--")
        </span>
         <span>      
            @Html.Label("IPs")
            @Html.DropDownListFor(model => model.IpId , Model.Ips,"--Select--")    
        </span>
        <br />

            <fieldset>
        <legend>Support Information</legend>

                        <span>
            @Html.LabelFor(model => model.SupportUsername)
            @Html.EditorFor(model => model.SupportUsername)
            @Html.ValidationMessageFor(model => model.SupportUsername)
        </span>


                <span>
            @Html.LabelFor(model => model.SupportPasswordHash)

   
            @Html.EditorFor(model => model.SupportPasswordHash)
            @Html.ValidationMessageFor(model => model.SupportPasswordHash)

        Show @Html.CheckBox("Example", false, new { onclick = "Show();" })
              </span>

   </fieldset>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    function Show() {
        var show = document.getElementById("Example").checked
        if (show) {
            document.getElementById("SupportPasswordHash").type = 'text';
        }
        else {

            document.getElementById("SupportPasswordHash").type = 'password';
        }
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</div>

SIL.Web/Views/Website/Delete.cshtml
@model IEnumerable<SIL.Domain.Website>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.SiteName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URL)
        </th>
@*        <th>
            @Html.DisplayNameFor(model => model.IPAddress)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.DatabaseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Version)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PSUOwned)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pingdom)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.SiteName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.URL)
            </td>
             <td>
                @*@Html.DisplayFor(modelItem => item.IPAddress)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatabaseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Version)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PSUOwned)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pingdom)
            </td>
         


            <td>
                @Html.ActionLink("Customer", "CustomerInfo", "Customer", new { id = item.CustomerId }, null) |
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.WebsiteId }) |
            @Html.ActionLink("Details", "Details", new { id = item.WebsiteId }) |
                  @Html.ActionLink("Delete", "Delete", new { id = item.WebsiteId },null)

            </td>
        </tr>
    }

</table>

SIL.Web/Views/Website/Details.cshtml
@model SIL.Web.ViewModels.WebsiteViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>WebsiteViewModel</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WebsiteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WebsiteId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CustomerId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerId)
    </div>


    <div class="display-label">
         @Html.DisplayNameFor(model => model.DatabaseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DatabaseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Version)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Version)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SiteName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SiteName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.URL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.URL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsActive)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsActive)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PSUOwned)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PSUOwned)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comments)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Pingdom)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pingdom)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div>
    @Html.Partial("_WebsiteIframe")
</div>

SIL.Web/Views/Website/Edit.cshtml
@model SIL.Web.ViewModels.WebsiteViewModel

@{
    ViewBag.Title = "Edit";
}

<h1>Edit</h1>
<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<span id="rightPane">
    </span>

<div>
@using (Html.BeginForm("Save", "Website")) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Website</legend>

        <span class="editor-label">
            @Html.LabelFor(model => model.SiteName)
            @Html.EditorFor(model => model.SiteName)
            @Html.ValidationMessageFor(model => model.SiteName)
        </span>

        <span>
            @Html.LabelFor(model => model.WebsitePath)
            @Html.EditorFor(model => model.WebsitePath)
            @Html.ValidationMessageFor(model => model.WebsitePath)
        </span>

        <span>
            @Html.LabelFor(model => model.WebsiteFolder)
            @Html.EditorFor(model => model.WebsiteFolder)
            @Html.ValidationMessageFor(model => model.WebsiteFolder)
        </span>

        <span>
            @Html.LabelFor(model => model.DatabaseName)
            @Html.EditorFor(model => model.DatabaseName)
            @Html.ValidationMessageFor(model => model.DatabaseName)
         </span>

        <span>
            @Html.LabelFor(model => model.Version)
            @Html.EditorFor(model => model.Version)
            @Html.ValidationMessageFor(model => model.Version)
        </span>
        <span>
            @Html.LabelFor(model => model.URL)
            @Html.EditorFor(model => model.URL)
            @Html.ValidationMessageFor(model => model.URL)
        </span>

         <span>
            @Html.LabelFor(model => model.IsActive)
              @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </span>

        <span>
            @Html.LabelFor(model => model.DomainControl)
            @Html.EditorFor(model => model.DomainControl)
            @Html.ValidationMessageFor(model => model.DomainControl)
         </span>

        <span>
            @Html.LabelFor(model => model.ServerName)
            @Html.EditorFor(model => model.ServerName)
            @Html.ValidationMessageFor(model => model.ServerName)
        </span>




        <span>
            @Html.LabelFor(model => model.Comments)
            @Html.EditorFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </span>

        <span>
            @Html.LabelFor(model => model.Pingdom)
            @Html.EditorFor(model => model.Pingdom)
            @Html.ValidationMessageFor(model => model.Pingdom)
        </span>

                        <span>
            @Html.Label("Customers")          
            @Html.DropDownListFor(model => model.CustomerId , Model.Customers,"--Select--")
        </span>
         <span>      
            @Html.Label("IPs")
            @Html.DropDownListFor(model => model.IpId , Model.Ips,"--Select--")    
        </span>
        <br />

            <fieldset>
        <legend>Support Information</legend>

                        <span>
            @Html.LabelFor(model => model.SupportUsername)
            @Html.EditorFor(model => model.SupportUsername)
            @Html.ValidationMessageFor(model => model.SupportUsername)
        </span>


                <span>
            @Html.LabelFor(model => model.SupportPasswordHash)

   
            @Html.EditorFor(model => model.SupportPasswordHash)
            @Html.ValidationMessageFor(model => model.SupportPasswordHash)

        Show @Html.CheckBox("Example", false, new { onclick = "Show();" })
              </span>

   </fieldset>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    function Show() {
        var show = document.getElementById("Example").checked
        if (show) {
            document.getElementById("SupportPasswordHash").type = 'text';
        }
        else {

            document.getElementById("SupportPasswordHash").type = 'password';
        }
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</div>

SIL.Web/Views/Website/Index.cshtml
@model IEnumerable<SIL.Domain.Website>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Websites</h1>
<div id="leftPane">
	<nav class="subMenu">
		<h3>Menu</h3>
		<ul>
			<li>@Html.ActionLink("Create New", "Create")</li>
		</ul>
		
	</nav>
</div>
<div id="rightPane">
<table id="tables">
        <thead>
    <tr>

        <th>
            @Html.DisplayName("Site Name")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URL)
        </th>
        <th>
            @Html.DisplayName("Database Name")
        </th>
        <th>
            @Html.DisplayName("Version No")
        </th>
        <th>
            @Html.DisplayName("Online")
        </th>
        <th>
            @Html.DisplayName("PSU Owned")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pingdom)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

   
    @foreach (var item in Model)
    {
        <tr>           
            <td>
                @Html.DisplayFor(modelItem => item.SiteName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.URL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatabaseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Version)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DomainControl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pingdom)
            </td>
            <td>
                @Html.ActionLink("Customer", "CustomerInfo", "Customer", new { id = item.CustomerId }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = item.WebsiteId }) |
                @Html.ActionLink("Details", "Details", new { id = item.WebsiteId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.WebsiteId },null)
            </td>
        </tr>
    }
 </tbody>
</table>
    </div>

SIL.Web/Views/Website/_WebsiteIframe.cshtml
@model SIL.Web.ViewModels.WebsiteViewModel

<div>
    <iframe src="@Model.URL" >

    </iframe>
</div>