SIL.Web/ViewModels/ServerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SIL.Web.ViewModels
{
    public class ServerViewModel
    {
        public int ServerId { get; set; }
        public string HostName { get; set; }
        public string FriendlyName { get; set; }
        public string IISVersionNo { get; set; }
        public string Description { get; set; }
    }
}

SIL.Web/Controllers/ServerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using SIL.CommadProcessor.Dispatcher;
using SIL.DataLayer.Repositories.Interfaces;
using SIL.DataLayer.Repository;
using SIL.Service.Commands.Server;
using SIL.Web.ViewModels;
using SIL.Web.Helpers;
using SIL.Domain;
using SIL.Web.Core;
using SIL.Web.Core.ActionFilters;
using SIL.Web.Core.Models;

namespace SIL.Web.Controllers
{
    [CompressResponse]
    [SILAuthorise(Roles.User, Roles.Admin)]
    public class ServerController : Controller
    {
        private readonly ICommandBus _commandBus;
        private readonly IServerRepository _serverRepository;

        public ServerController(ICommandBus commandBus, IWebsiteRepository ipRepository, IServerRepository serverRepository)
        {
            this._commandBus = commandBus;
            this._serverRepository = serverRepository;
        }

        public ActionResult Index()
        {
            var server = _serverRepository.GetAll();
            return View(server);
        }


        public ActionResult Create()
        {
            var viewModel = new ServerViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Save(ServerViewModel serv)
        {
            if (ModelState.IsValid)
            {
                var command = Mapper.Map<ServerViewModel, CreateOrUpdateServerCommand>(serv);
                var result = _commandBus.Submit(command);

                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
            }


            //web.Customer = serv..To(serv.WebsiteId);
            if (serv.ServerId == 0)
            {
                return View("Create", serv);
            }
            else
            {
                return View("Edit", serv);
            }
        }

        public ActionResult Edit(int id)
        {
            var serv = _serverRepository.GetById(id);
            var viewModel = Mapper.Map<Server, ServerViewModel>(serv);
            return View(viewModel);
        }



        public ActionResult Delete(int id)
        {
            var command = new DeleteServerCommand { ServerId = id };
            var result = _commandBus.Submit(command);
            var server = _serverRepository.GetAll();
            return View(server);
        }

        public ActionResult Details(int id = 0)
        {
            var server = _serverRepository.GetById(id);
            var viewModel = Mapper.Map<Server, ServerViewModel>(server);
            return View(viewModel);
        }


    }
}

SIL.Web/Views/Server/Create.cshtml
@model SIL.Web.ViewModels.ServerViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="pull-left">Create</h1>
   

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<div id="rightPane">


@using (Html.BeginForm("Save", "Server"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Server</legend>

        <span class="editor-label">
                     @Html.Label("Host Name")
            @Html.EditorFor(model => model.HostName)
            @Html.ValidationMessageFor(model => model.HostName)
        </span>


        <span>
                       @Html.Label("Friendly Name")
            @Html.EditorFor(model => model.FriendlyName)
            @Html.ValidationMessageFor(model => model.FriendlyName)
        </span>
        <span>
                  @Html.Label("IIS Version")
            @Html.EditorFor(model => model.IISVersionNo)
            @Html.ValidationMessageFor(model => model.IISVersionNo)
        </span>
        <span>
          @Html.Label("Description")


            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </span>

             <span>
            <input type="submit" value="Create" class="btn green pull-right" />
        </span>
    </fieldset>
}

       @Html.ActionLink("Back to List", "Index", null, new { @class = "btn red pull-left" })

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIL.Web/Views/Server/Delete.cshtml
@model IEnumerable<SIL.Domain.Server>

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HostName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HostName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FriendlyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ServerId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ServerId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ServerId })
        </td>
    </tr>
}

</table>

SIL.Web/Views/Server/Details.cshtml
@model SIL.Web.ViewModels.ServerViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>ServerViewModel</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ServerId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ServerId)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.HostName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HostName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FriendlyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FriendlyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SIL.Web/Views/Server/Edit.cshtml
@model SIL.Web.ViewModels.ServerViewModel

@{
    ViewBag.Title = "Edit";
}

<h1>Edit</h1>

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<div id="rightPane">


@using (Html.BeginForm("Save", "Server"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Server</legend>

        <span class="editor-label">
                     @Html.Label("Host Name")
            @Html.EditorFor(model => model.HostName)
            @Html.ValidationMessageFor(model => model.HostName)
        </span>


        <span>
                       @Html.Label("Friendly Name")
            @Html.EditorFor(model => model.FriendlyName)
            @Html.ValidationMessageFor(model => model.FriendlyName)
        </span>
        <span>
                  @Html.Label("IIS Version")
            @Html.EditorFor(model => model.IISVersionNo)
            @Html.ValidationMessageFor(model => model.IISVersionNo)
        </span>
        <span>
          @Html.Label("Description")


            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </span>

             <span>
            <input type="submit" value="Create" class="btn green pull-right" />
        </span>
    </fieldset>
}

       @Html.ActionLink("Back to List", "Index", null, new { @class = "btn red pull-left" })

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
    </div>

SIL.Web/Views/Server/Edit1.cshtml
@model SIL.Web.ViewModels.ServerViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<div id="rightPane">


@using (Html.BeginForm("Save", "Server"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Server</legend>

        <span class="editor-label">
                     @Html.Label("Host Name")
            @Html.EditorFor(model => model.HostName)
            @Html.ValidationMessageFor(model => model.HostName)
        </span>


        <span>
                       @Html.Label("Friendly Name")
            @Html.EditorFor(model => model.FriendlyName)
            @Html.ValidationMessageFor(model => model.FriendlyName)
        </span>
        <span>
                  @Html.Label("IIS Version")
            @Html.EditorFor(model => model.IISVersionNo)
            @Html.ValidationMessageFor(model => model.IISVersionNo)
        </span>
        <span>
          @Html.Label("Description")


            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </span>

             <span>
            <input type="submit" value="Create" class="btn green pull-right" />
        </span>
    </fieldset>
}

       @Html.ActionLink("Back to List", "Index", null, new { @class = "btn red pull-left" })

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIL.Web/Views/Server/Index.cshtml
@model IEnumerable<SIL.Domain.Server>

@{
    ViewBag.Title = "Index";
}

<h1>Servers</h1>

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
		<ul>
			<li>@Html.ActionLink("Create New", "Create")</li>
		</ul>
	</nav>
</div>
<div id="rightPane">
<table id="tables">
	<thead>
		<tr>
        <th>
            @Html.Label("Host Name")
        </th>
        <th>
            @Html.Label("Friendly Name")
        </th>
        <th>
           @Html.Label("IIS Version")
        </th>
        <th>
          @Html.Label("Description")
        </th>
                    <th></th>
		</tr>
	</thead>
	<tbody>


@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HostName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FriendlyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IISVersionNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ServerId }) |
            @Html.ActionLink("Details", "Details", new {id=item.ServerId  }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ServerId  })
        </td>
    </tr>
}

	</tbody>

</table>
</div>

SIL.Web/Views/Server/Index1.cshtml
@model IEnumerable<SIL.Domain.Server>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Servers</h1>

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
		<ul>
			<li>@Html.ActionLink("Create New", "Create")</li>
		</ul>
	</nav>
</div>
<div id="rightPane">
<table id="tables">
	<thead>
		<tr>
			<th>
            @Html.DisplayNameFor(model => model.HostName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
               @Html.DisplayNameFor(model => model.I)
        </th>
		</tr>
	</thead>
	<tbody>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HostName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FriendlyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ServerId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ServerId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ServerId })
        </td>
    </tr>
}
	</tbody>

</table>
</div>