SIL.Web/ViewModels/ReleaseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SIL.Web.ViewModels
{
    public class ReleaseViewModel
    {
        public int ReleaseId { get; set; }
    [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd.MM.yy}", ApplyFormatInEditMode = true)]
        public DateTime LiveDate { get; set; }
  [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd.MM.yy}", ApplyFormatInEditMode = true)]
        public DateTime StagingDate { get; set; }
    [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd.MM.yy}", ApplyFormatInEditMode = true)]
        public DateTime DevDate { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public StatusList Statuses { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> Websites { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> RType { get; set; }

        public int ReleaseTypeId { get; set; }
        public int WebsiteId { get; set; }

        [MaxLength(10)]
        public string BuildVersionNo { get; set; }
        public string ReleaseDescription1 { get; set; }
        public string ReleaseDescription2 { get; set; }
        public string ReleaseDescription3 { get; set; }
        public string DbVersionNo { get; set; }
        public bool Build { get; set; }
        public bool DB { get; set; }
        public bool Script { get; set; }
        public bool Design { get; set; }
        public bool Content { get; set; }
        public DateTime CreatedDate { get; set; }



        public enum StatusList
        {
            prerelease = 1,
            release = 2
        }



    }
}

SIL.Web/Controllers/ReleaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using SIL.CommadProcessor.Dispatcher;
using SIL.DataLayer.Repositories.Interfaces;
using SIL.DataLayer.Repository;
using SIL.Service.Commands.Release;
using SIL.Web.ViewModels;
using SIL.Web.Helpers;
using SIL.Domain;
using SIL.Web.Core;
using SIL.Web.Core.ActionFilters;
using SIL.Web.Core.Models;

namespace SIL.Controllers
{
    [CompressResponse]
    [SILAuthorise(Roles.User, Roles.Admin)]
    public class ReleaseController : Controller
    {
        private readonly ICommandBus _commandBus;
        private readonly IReleaseTypeRepository _releaseTypeRepository;
        private readonly IReleaseRepository _releaseRepository;
        private readonly IWebsiteRepository _websiteRepository;

        public ReleaseController(ICommandBus commandBus, IWebsiteRepository websiteRepository, IReleaseRepository releaseRepository, IReleaseTypeRepository releaseTypeRepository)
        {
            this._websiteRepository = websiteRepository;
            this._commandBus = commandBus;
            this._releaseRepository = releaseRepository;
            this._releaseTypeRepository = releaseTypeRepository;
        }

        public ActionResult Index()
        {
            var release = _releaseRepository.GetAll();

            //set start date and end date to ViewBag dictionary
            ViewBag.LiveDate = DateTime.Now.ToShortDateString();
    
            return View(release);
        }

        public ActionResult Details(int id =0)
        {
            //var website = _websiteAcceessor.Repo.Find(id);
            return View();
        }


        public ActionResult Create()
        {
            var viewModel = new ReleaseViewModel();
            var web = _websiteRepository.GetAll();
            var rt = _releaseTypeRepository.GetAll();
            var rts = new ReleaseType();
            viewModel.RType = rt.ToSelectItemList( r => r.Name, r => r.ReleaseTypeId.ToString());
            viewModel.Websites = web.ToSelectListOfWebsites(-1);
            viewModel.DevDate = DateTime.Now;
            viewModel.StagingDate = DateTime.Now;
            viewModel.LiveDate = DateTime.Now;
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(ReleaseViewModel rh)
        {

            if (ModelState.IsValid)
            {

                //ReleaseViewModel.StatusList d = rh.Statuses;

                //rh.Statuses = rh.Statuses;
                var command = Mapper.Map<ReleaseViewModel, CreateOrUpdateReleaseCommand>(rh);
                var result = _commandBus.Submit(command);

                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            var web = _websiteRepository.GetAll();
            var rt = _releaseTypeRepository.GetAll();
            rh.Websites = web.ToSelectListOfWebsites(rh.ReleaseId);
            rh.RType = rt.ToSelectItemList(r => r.Name, r => r.ReleaseTypeId.ToString());


            if (rh.ReleaseId  == 0)
            {
                return View("Create", web);
            }
            else
            {
                return View("Edit", web);
            }            
        }

        public ActionResult Edit(int id)      
        {
            var release = _releaseRepository.GetById(id);
            var viewModel = Mapper.Map<Release, ReleaseViewModel>(release);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(int id, Website web)
        {
           // _websiteAcceessor.Repo.InsertOrUpdate(web);
            //_websiteAcceessor.Save();
            return RedirectToAction("Index");
        }
    }
}

SIL.Web/Views/Release/Create.cshtml
@model SIL.Web.ViewModels.ReleaseViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="pull-left">Create</h1>



<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<div id="rightPane">


@using (Html.BeginForm("Create", "Release"))
{
    @Html.ValidationSummary(true)



          @Html.Partial("_CreateOrEdit",Model) 

 }

@section Scripts {
    @Scripts.Render("~/bundles/modernizr")

<script >
    $().ready(function () {
        $('.datepicker').datepicker({
            dateFormat: 'dd/mm/yy',
            buttonImage: '@Url.Content("~/Images/calendar.gif")',
                buttonImageOnly: true,
                showOn: "button"
            });
        });
</script>

}


</div>

SIL.Web/Views/Release/Delete.cshtml
@model IEnumerable<SIL.Domain.Release>

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ReleaseViewModel</legend>
    
@*    <div class="display-label">
         @Html.DisplayNameFor(model => model.)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseDate)
    </div>*@

@*    <div class="display-label">
         @Html.DisplayNameFor(model => model.Notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Notes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WebsiteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WebsiteId)
    </div>*@
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
    @Html.ActionLink("Back to List", "Index", null,   new  { @class = "btn red pull-left" })
    </p>
}

SIL.Web/Views/Release/Details.cshtml
@model SIL.Web.ViewModels.ReleaseViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>ReleaseViewModel</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LiveDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LiveDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StagingDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StagingDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Notes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WebsiteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WebsiteId)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index", null,   new  { @class = "btn red pull-left" })
</p>

SIL.Web/Views/Release/Edit.cshtml
@model SIL.Web.ViewModels.ReleaseViewModel

@{
    ViewBag.Title = "Edit";
}

<h1>Edit</h1>

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
	</nav>
</div>
<span id="rightPane">
    </span>
@using (Html.BeginForm("Create", "Release"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Release</legend>

        <span>
            @Html.LabelFor(model => model.ReleaseId)
            @Html.EditorFor(model => model.ReleaseId)
            @Html.ValidationMessageFor(model => model.ReleaseId)
        </span>

        <span>
            @Html.LabelFor(model => model.LiveDate)
            @Html.EditorFor(model => model.LiveDate)
            @Html.ValidationMessageFor(model => model.LiveDate)
        </span>

        <span>
            @Html.LabelFor(model => model.StagingDate)
            @Html.EditorFor(model => model.StagingDate)
            @Html.ValidationMessageFor(model => model.StagingDate)
        </span>

        <span>
            @Html.LabelFor(model => model.DevDate)
            @Html.EditorFor(model => model.DevDate)
            @Html.ValidationMessageFor(model => model.DevDate)
        </span>

        <span>
            @Html.LabelFor(model => model.Notes)
            @Html.EditorFor(model => model.Notes)
            @Html.ValidationMessageFor(model => model.Notes)
        </span>

        <span>
            @Html.LabelFor(model => model.Status)
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </span>

        <span>
            @Html.LabelFor(model => model.ReleaseTypeId)
            @Html.EditorFor(model => model.ReleaseTypeId)
            @Html.ValidationMessageFor(model => model.ReleaseTypeId)
        </span>

        <span>
            @Html.LabelFor(model => model.WebsiteId)
            @Html.EditorFor(model => model.WebsiteId)
            @Html.ValidationMessageFor(model => model.WebsiteId)
        </span>

        <span>
            @Html.LabelFor(model => model.BuildVersionNo)
            @Html.EditorFor(model => model.BuildVersionNo)
            @Html.ValidationMessageFor(model => model.BuildVersionNo)
        </span>

        <span>
            @Html.LabelFor(model => model.ReleaseDescription1)
            @Html.EditorFor(model => model.ReleaseDescription1)
            @Html.ValidationMessageFor(model => model.ReleaseDescription1)
        </span>

        <span>
            @Html.LabelFor(model => model.ReleaseDescription2)
            @Html.EditorFor(model => model.ReleaseDescription2)
            @Html.ValidationMessageFor(model => model.ReleaseDescription2)
        </span>

        <span>
            @Html.LabelFor(model => model.ReleaseDescription3)
            @Html.EditorFor(model => model.ReleaseDescription3)
            @Html.ValidationMessageFor(model => model.ReleaseDescription3)
        </span>

        <span>
            @Html.LabelFor(model => model.DbVersionNo)
           @Html.EditorFor(model => model.DbVersionNo)
            @Html.ValidationMessageFor(model => model.DbVersionNo)
        </span>

        <span>
            @Html.LabelFor(model => model.Build)
            @Html.EditorFor(model => model.Build)
            @Html.ValidationMessageFor(model => model.Build)
        </span>

        <span>
            @Html.LabelFor(model => model.DB)
            @Html.EditorFor(model => model.DB)
            @Html.ValidationMessageFor(model => model.DB)
        </span>

        <span>
            @Html.LabelFor(model => model.Script)
            @Html.EditorFor(model => model.Script)
            @Html.ValidationMessageFor(model => model.Script)
        </span>

        <span>
            @Html.LabelFor(model => model.Design)
            @Html.EditorFor(model => model.Design)
            @Html.ValidationMessageFor(model => model.Design)
        </span>

        <span>
            @Html.LabelFor(model => model.Content)
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </span>

        <p>
                       <input type="submit" value="Save" class="btn green pull-right" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", null,   new  { @class = "btn red pull-left" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIL.Web/Views/Release/Edit1.cshtml
@model SIL.Domain.Release

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
}
    <fieldset>
        <legend>ReleaseHistory</legend>

  @*      @Html.HiddenFor(model => model.ReleaseHistoryId)

        <div class="editor-label">
            @Html.LabelFor(model => model.BuildVersionNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BuildVersionNo)
            @Html.ValidationMessageFor(model => model.BuildVersionNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseDescription)
            @Html.ValidationMessageFor(model => model.ReleaseDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DbVersionNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DbVersionNo)
            @Html.ValidationMessageFor(model => model.DbVersionNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LatestBuildOnStaging)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LatestBuildOnStaging)
            @Html.ValidationMessageFor(model => model.LatestBuildOnStaging)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LatestDesignOnStaging)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LatestDesignOnStaging)
            @Html.ValidationMessageFor(model => model.LatestDesignOnStaging)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RollbackConsiderations)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RollbackConsiderations)
            @Html.ValidationMessageFor(model => model.RollbackConsiderations)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BuildBy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BuildBy)
            @Html.ValidationMessageFor(model => model.BuildBy)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DesignBy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DesignBy)
            @Html.ValidationMessageFor(model => model.DesignBy)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseDate)
            @Html.ValidationMessageFor(model => model.ReleaseDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notes)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Notes)
            @Html.ValidationMessageFor(model => model.Notes)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.WebsiteId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WebsiteId)
            @Html.ValidationMessageFor(model => model.WebsiteId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}*@

<div>
    @Html.ActionLink("Back to List", "Index", null,   new  { @class = "btn red pull-left" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIL.Web/Views/Release/Index.cshtml
@model IEnumerable<SIL.Domain.Release>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Releases</h1>

<div id="leftPane">
	<nav class="subMenu">
	<h3>Actions</h3>
		<ul>
			<li>@Html.ActionLink("Create New", "Create")</li>
		</ul>
	</nav>
</div>
<div id="rightPane">
<table id="tables">
	<thead>
		<tr>
         <th>
            @Html.DisplayName("KO Date")
        </th>
			<th>
            @Html.DisplayName("Release Date")
        </th>
        <th>
            @Html.DisplayName("Staging Date")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseStatus)
        </th>
        <th></th>
    </tr>
	</thead>
	<tbody>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LiveDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StagingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ReleaseId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ReleaseId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ReleaseId }, null)
        </td>
    </tr>
}

</tbody>

</table>
</div>

SIL.Web/Views/Release/_CreateOrEdit.cshtml
@model SIL.Web.ViewModels.ReleaseViewModel
@using SIL.Web.Helpers

<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("Create", "Release"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Release</legend>

        <span>
            @Html.Label("Website")
            @Html.DropDownListFor(model => model.WebsiteId, Model.Websites, "--Select--")
            @Html.ValidationMessageFor(model => model.WebsiteId)
        </span>


        <span>
            @Html.Label("Type Of Release")
            @Html.DropDownListFor(model => model.ReleaseTypeId, Model.RType, "--Select--")
        </span>

        <span>
            @Html.Label("Dev Release Date")
            @Html.EditorFor(model => model.DevDate, new { @class = "datepicker" })

        </span>

        <span>
            @Html.Label("Staging Release Date")
            @Html.EditorFor(model => model.StagingDate, new { @class = "datepicker" })


        </span>


        <span>
            @Html.Label("Live Release Date")
            @Html.EditorFor(model => model.LiveDate, new { @class = "datepicker" })

        </span>

        <span>
            @Html.LabelFor(model => model.Notes)
            @Html.EditorFor(model => model.Notes)
            @Html.ValidationMessageFor(model => model.Notes)
        </span>

        <span>
            @Html.LabelFor(model => model.Status)
            @Html.DropDownListFor(model => model.Statuses, Model.Statuses.ToSelectList(addPleaseSelect: true))
        </span>

        <input type="submit" value="Create" class="btn green pull-right" />
    </fieldset>
    
    
}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn red pull-left" })

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $().ready(function () {
            $('.datepicker').datepicker({
                dateFormat: 'dd/mmm/yy',
                buttonImage: '@Url.Content("~/Images/calendar.gif")',
            buttonImageOnly: true,
            showOn: "button"
        });
    });
    </script>
}